project_id = "xqihoxgwxgiwwbybztbp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = false
enable_anonymous_sign_ins = false
enable_email_confirmations = false
enable_signup = true
minimum_password_length = 6

[functions.admin-auth]
verify_jwt = false

[functions.blog-management]
verify_jwt = false